site_name: My Project Documentation
site_description: A detailed description of my project
theme: material

nav:
  - Главная страница: index.md
  - Обзор: overview.md
  - Начало работы: getting-started.md
  - Аутентификация и авторизация: auth.md
  - Справочник API: swagger-ui/index.html
  - Примеры использования API: examples.md
  - История изменений: changelog.md
  - Контакты: contacts.md
  - Глоссарий: glossary.md
